---
- name: Extract aggregator binary
  copy:
    src: "/tmp/{{ m3db_binaries_folder_name }}/m3aggregator"
    dest: "{{ m3db_binaries }}/"
    mode: '0750'
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
    remote_src: true

- name: Deploy m3aggregator config file
  template:
    src: m3aggregator.yml.j2
    dest: "{{ m3db_config_folder }}/m3aggregator.yml"
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
    mode: 0644
    trim_blocks: yes
    lstrip_blocks: yes
  notify: Restart m3aggregator

- name: Create systemd unit file for m3aggregator
  template:
    src: m3aggregator.service.j2
    dest: /etc/systemd/system/m3aggregator.service
    owner: root
    group: root
    mode: 0644
  notify: Restart m3aggregator
