---
- name: Deploy coordinator config file
  template:
    src: m3coordinator.yml
    dest: "{{ m3db_config_folder }}/m3coordinator.yml"
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
    mode: 0644
  notify:
    - Restart m3coordinator

- name: Create systemd unit file for coordinator
  template:
    src: m3coordinator.service.j2
    dest: /etc/systemd/system/m3coordinator.service
    owner: root
    group: root
    mode: 0644
  notify: Restart m3coordinator
