---
- name: Extract coordinator binary
  copy:
    src: "/tmp/{{ m3db_binaries_folder_name }}/m3coordinator"
    dest: "{{ m3db_binaries }}/"
    mode: '0750'
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
    remote_src: true

- name: Deploy coordinator config file
  template:
    src: m3coordinator.yml.j2
    dest: "{{ m3db_config_folder }}/m3coordinator.yml"
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
    mode: 0644
  notify: Restart m3coordinator

- name: Create systemd unit file for coordinator
  template:
    src: m3coordinator.service.j2
    dest: /etc/systemd/system/m3coordinator.service
    owner: root
    group: root
    mode: 0644
  notify: Restart m3coordinator