---
- name: Apply recommended sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: false
  with_items: "{{ custom_sysctl }}"
  notify: Reload systctl

- name: Extract dbnode binary
  copy:
    src: "/tmp/{{ m3db_binaries_folder_name }}/m3dbnode"
    dest: "{{ m3db_binaries }}/"
    mode: '0750'
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
    remote_src: true

- name: Deploy m3db node config file
  template:
    src: m3dbnode.yml.j2
    dest: "{{ m3db_config_folder }}/m3dbnode.yml"
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
    mode: 0644
    trim_blocks: yes
    lstrip_blocks: yes
  notify: Restart m3dbnode

- name: Create systemd unit file for m3dbnode
  template:
    src: m3dbnode.service.j2
    dest: /etc/systemd/system/m3dbnode.service
    owner: root
    group: root
    mode: 0644
  notify: Restart m3dbnode