---
# tasks file for m3db
- include_tasks: preinstall.yml
  args:
    apply:
      tags:
        - install_coordinator
        - install_dbnode
  tags:
    - install_coordinator
    - install_dbnode

- name: Deploy coordinator
  include_tasks: install_coordinator.yml
  agrs:
    apply:
      tags:
        - install_coordinator
  tags:
    - install_coordinator
  when: inventory_hostname in groups['m3coordinator']

- name: Deploy dbnode
  include_tasks: install_dbnode.yml
  agrs:
    apply:
      tags:
        - install_dbnode
  tags:
    - install_dbnode
  when: inventory_hostname in groups['m3dbnode']

