---
- name: Create m3db system group
  group:
    name: "{{ m3db_system_group }}"
    state: present
    system: true
  when: m3db_system_group != "root"

- name: Create m3db system user
  user:
    name: "{{ m3db_system_user }}"
    groups: "{{ m3db_system_group }}"
    append: true
    shell: /sbin/nologin
    system: true
    createhome: false
  when: m3db_system_user != "root"

- name: Creating {{ m3db_binaries }}
  file:
    path: "{{ m3db_binaries }}"
    state: directory
    mode: '0755'
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"

- name: Creating {{ m3db_config_folder }}
  file:
    path: "{{ m3db_config_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"

- name: Download sources from {{ m3db_download_url }}
  unarchive: 
    src: "{{ m3db_download_url }}"
    dest: "/tmp/m3db"
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
    remote_src: true
  when:
    - not ansible_check_mode

- name: Extract binaries
  copy:
    src: "/tmp/m3db/{{ m3db_binaries_folder_name }}/"
    dest: "{{ m3db_binaries }}/"
    mode: '0755'
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"

- name: Apply recommended sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/systctl.d/99-m3db-custom_tune.conf
    reload: no
  with_items: "{{ custom_sysctl }}"
  notify:
    - reload sysctl.conf
