---
- name: Create m3db system group
  group:
    name: "{{ m3db_system_group }}"
    state: present
    system: true
  when: m3db_system_group != "root"

- name: Create m3db system user
  user:
    name: "{{ m3db_system_user }}"
    groups: "{{ m3db_system_group }}"
    append: true
    shell: /sbin/nologin
    system: true
    createhome: false
  when: m3db_system_user != "root"

- name: Creating m3db directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
  loop:
    - "{{ m3db_binaries }}"
    - "{{ m3db_config_folder }}"
    - "{{ m3db_data_dir }}"
    - "{{ m3db_kv_dir }}"

- name: Download sources from {{ m3db_download_url }}
  unarchive:
    src: "{{ m3db_download_url }}"
    dest: "/tmp/"
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"
    remote_src: true
  when:
    - not ansible_check_mode

- name: Extract binaries
  copy:
    src: "/tmp/{{ m3db_binaries_folder_name }}/"
    remote_src: true
    dest: "{{ m3db_binaries }}/"
    mode: '0750'
    owner: "{{ m3db_system_user }}"
    group: "{{ m3db_system_group }}"

- name: Apply recommended sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    # sysctl_file: /etc/systctl.d/99-m3db-custom_tune.conf
    reload: false
  with_items: "{{ custom_sysctl }}"
  notify:
    - reload sysctl.conf
